[project]
name = 'BitDAO-Invest'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.bit-invest-dao]
path = 'contracts/bit-invest-dao.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
